language: python
sudo: true

services:
  - docker
  
  script:
    - docker run -it -v /$(pwd):/dev/shm/ kineticskunk/node-chrome:3.11.1-toolium bash
    - cd dev/shm/Sprint_review_web_automation
    - behave
