language: python
sudo: true
python:
    - "2.7"
 
services:
    - docker
    
before_install:
    - docker pull kineticskunk/node-chrome:3.11.1-toolium
    - docker run -it -v /$(pwd):/dev/shm/ kineticskunk/node-chrome:3.11.1-toolium < test.sh
    
script:
    - bash tests.sh

    - cd dev/shm/Sprint_review_web_automation
    - behave
