language: python
sudo: flase
python:
    - "2.7"
 
services:
    - docker
    
script:
#     - docker pull kineticskunk/node-chrome:3.11.1-toolium
    - sudo docker run -it -v /$(pwd):/dev/shm/ kineticskunk/node-chrome:3.11.1-toolium bash -c "cd dev/shm/; 
      sudo apt-get update && sudo apt-get upgrade -y; 
      sudo behave"
    
# after_script:
#     - bash test.sh

#     - cd dev/shm/Sprint_review_web_automation
#     - behave
