language: python
sudo: true
python:
    - "2.7"
 
services:
    - docker
    
script:
    - docker pull kineticskunk/node-chrome:3.11.1-toolium
    - docker run -it -v /$(pwd):/dev/shm/ kineticskunk/node-chrome:3.11.1-toolium bahs && cd dev/shm/Sprint_review_web_automation
    
after_script:
    - bash tests.sh

#     - cd dev/shm/Sprint_review_web_automation
#     - behave
