language: python
sudo: true
python:
    - "3.6"
    - "2.7"
 
services:
    - docker
  
before_install:
    - docker pull kineticskunk/node-chrome:3.11.1-toolium
    - docker ps -a

env:
  global:
#     - secure: L/aGHl+XZ2tyeZ0xZTkKPySfsVZxkQt9Y3naN0icMu8DoXP83eUQ/gKooEKP0i0XTvwslCGa808UyZ99mWAdZ/WBA23i7q3fCLHwMcA7EcRsDky8vv6nMu00jTwLEX2ly+3+jc4xZV7ZO7KJNBRBcSD78L2KiMiRUzZ+WFZVrZ0=
#     - secure: T9Ur8o93Bs42r2De53U97oheh/E+P9VDpuRYHUtr5YoxU/n4sALcz3FfyJ6HOcuDctIXb26MvNrzvf9abaxNFf4QapqVlWW6Fj8xHA9x55eRjz4QasyM1nk7gqhlZ2HZuvxqhEcgvfirn7FGb9bIEuBVmFaJtqURp2JwEO4ABdQ=

    - username: "xolanimxoxozi"
    - access_key: "3bd6fd59-45ea-4b29-9c9c-6c5b0710caae"

script:
    - docker run -it -v /$(pwd):/dev/shm/ kineticskunk/node-chrome:3.11.1-toolium bash
    - cd dev/shm/Sprint_review_web_automation
    - behave
