language: python
sudo: true
python:
    - "2.7"
 
services:
    - docker
    
script:
#     - docker pull kineticskunk/node-chrome:3.11.1-toolium
    - sudo docker run -it -v /$(pwd):/dev/shm/ xolanimxoxozi/node-chrome bash -c "cd dev/shm/; behave"
    
# after_script:
#     - bash test.sh

#     - cd dev/shm/Sprint_review_web_automation
#     - behave
